name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: print job details
        run: |
          echo "github_ref ${{ github.ref }}"
          echo "github_event_name ${{ github.event_name }}"

      - name: npm install
        run: npm ci

      - name: pull backpack
        run: npm run pull-backpack

      - name: transpile
        run: npm run transpile

      - name: lint
        run: npm run lint

      - name: jest
        run: npm run test
